#!/usr/bin/env bash
# Build the firmware.
#
# First-time use (interactive):
#   ./build.sh                    Prompts for Wi-Fi SSID/PSK, saves them
#                                 to senselink.local.conf (gitignored), then
#                                 builds. Subsequent runs reuse the conf.
#
# Re-prompt and overwrite saved creds:
#   ./build.sh setup
#
# Force a clean rebuild:
#   ./build.sh clean
#
# Non-interactive (CI / scripted), no conf file written:
#   SENSELINK_WIFI_SSID="..." SENSELINK_WIFI_PSK="..." ./build.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$REPO_ROOT/build"
CONF_FILE="$REPO_ROOT/senselink.local.conf"

PICO_SDK_PATH="${PICO_SDK_PATH:-$HOME/.pico-sdk/pico-sdk}"
PICO_TOOLCHAIN_PATH="${PICO_TOOLCHAIN_PATH:-$HOME/.pico-sdk/toolchain/arm-14.2}"

# ── Colors / logging ──────────────────────────────────────────────────────
# $'...' so escape sequences are real ESC bytes, usable in `cat` heredocs.
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
CYAN=$'\033[0;36m'; BOLD=$'\033[1m'; NC=$'\033[0m'
info() { printf '%s[*]%s %s\n' "$CYAN" "$NC" "$*"; }
ok()   { printf '%s[ok]%s %s\n' "$GREEN" "$NC" "$*"; }
warn() { printf '%s[!]%s %s\n' "$YELLOW" "$NC" "$*"; }
die()  { printf '%s[err]%s %s\n' "$RED" "$NC" "$*" >&2; exit 1; }

# ── Preflight ──────────────────────────────────────────────────────────────
[[ -d "$PICO_SDK_PATH" ]] \
  || die "PICO_SDK_PATH=$PICO_SDK_PATH not found"
[[ -d "$PICO_TOOLCHAIN_PATH/bin" ]] \
  || die "PICO_TOOLCHAIN_PATH=$PICO_TOOLCHAIN_PATH/bin not found"

export PICO_SDK_PATH PICO_TOOLCHAIN_PATH
export PATH="$PICO_TOOLCHAIN_PATH/bin:$PATH"

# ── Argument parsing ───────────────────────────────────────────────────────
DO_CLEAN=0
DO_SETUP=0
EXTRA_CMAKE_FLAGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    setup)   DO_SETUP=1 ;;
    clean)   DO_CLEAN=1 ;;
    -D*)     EXTRA_CMAKE_FLAGS+=("$1") ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \?//'
      exit 0 ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

# ── Credentials: env > conf file > interactive prompt ──────────────────────
prompt_credentials() {
  echo
  echo -e "${BOLD}── Wi-Fi credentials for the Pico ──${NC}"
  echo "Stored to $CONF_FILE (gitignored, mode 0600)."
  echo "You can edit or delete that file to change them later."
  echo
  local ssid psk psk2
  while :; do
    read -rp "SSID: " ssid
    [[ -n "$ssid" ]] && break
    warn "SSID can't be empty"
  done
  while :; do
    read -rsp "PSK (will not be shown): " psk
    echo
    read -rsp "PSK (again):              " psk2
    echo
    if [[ -z "$psk" ]]; then
      warn "PSK can't be empty"; continue
    fi
    if [[ "$psk" != "$psk2" ]]; then
      warn "PSKs don't match, try again"; continue
    fi
    break
  done

  # Write atomically with 0600
  umask 077
  cat > "$CONF_FILE.tmp" <<EOF
# senselink local config — do not commit.
# Generated by build.sh. Re-run \`./build.sh setup\` to change.
SENSELINK_WIFI_SSID=$(printf '%q' "$ssid")
SENSELINK_WIFI_PSK=$(printf '%q' "$psk")
EOF
  mv "$CONF_FILE.tmp" "$CONF_FILE"
  chmod 0600 "$CONF_FILE"
  ok "saved credentials to $CONF_FILE"
}

if (( DO_SETUP )); then
  prompt_credentials
  echo
  info "Setup complete. Run ./build.sh to build."
  exit 0
fi

# Priority: explicit env vars > conf file > prompt
if [[ -n "${SENSELINK_WIFI_SSID:-}" && -n "${SENSELINK_WIFI_PSK:-}" ]]; then
  : # use env vars as-is
elif [[ -f "$CONF_FILE" ]]; then
  # shellcheck source=/dev/null
  set -a; source "$CONF_FILE"; set +a
else
  if [[ ! -t 0 ]]; then
    die "no credentials available. Either:
       1) Run \`./build.sh\` interactively to save them once, or
       2) Pass SENSELINK_WIFI_SSID and SENSELINK_WIFI_PSK as env vars."
  fi
  prompt_credentials
  # shellcheck source=/dev/null
  set -a; source "$CONF_FILE"; set +a
fi

[[ -n "${SENSELINK_WIFI_SSID:-}" ]] || die "SENSELINK_WIFI_SSID is empty"
[[ -n "${SENSELINK_WIFI_PSK:-}"  ]] || die "SENSELINK_WIFI_PSK is empty"

# ── Build ──────────────────────────────────────────────────────────────────
if (( DO_CLEAN )); then
  info "cleaning build/"
  rm -rf "$BUILD_DIR"
fi

# Reconfigure when build dir is fresh or when extra flags are passed
NEED_CONFIGURE=0
[[ ! -d "$BUILD_DIR" ]] && NEED_CONFIGURE=1
(( ${#EXTRA_CMAKE_FLAGS[@]} > 0 )) && NEED_CONFIGURE=1

if (( NEED_CONFIGURE )); then
  info "configuring (cmake)"
  cmake -G Ninja -S "$REPO_ROOT" -B "$BUILD_DIR" \
    -DSENSELINK_SKEL=ON \
    "-DSENSELINK_WIFI_SSID=${SENSELINK_WIFI_SSID}" \
    "-DSENSELINK_WIFI_PSK=${SENSELINK_WIFI_PSK}" \
    "${EXTRA_CMAKE_FLAGS[@]}" \
    >/dev/null
fi

info "building"
cmake --build "$BUILD_DIR" -- -j"$(nproc)" 2>&1 \
  | grep -E '^\[|error:|warning:|FAILED' || true

UF2="$BUILD_DIR/senselink-skel.uf2"
BL="$BUILD_DIR/ds5-bridge.uf2"
echo
if [[ -f "$UF2" ]]; then
  ok "skeleton build: $UF2 ($(du -h "$UF2" | cut -f1))"
fi
if [[ -f "$BL" ]]; then
  ok "baseline build: $BL ($(du -h "$BL" | cut -f1))"
fi

cat <<EOF

${BOLD}── Flash the Pico 2W ──${NC}
1. Hold BOOTSEL on the Pico, plug into USB.
2. It mounts as RPI-RP2.
3. Drag this file onto it:
   ${UF2}
4. After flashing, power it from any USB source (wall charger is fine).
5. From your Linux host: usbip list -r <pico-ip>

EOF
