/*
 * Wi-Fi station bring-up with multi-network support.
 *
 * On boot:
 *   1. Scan all visible 2.4 GHz APs.
 *   2. Intersect with our compile-time `senselink_networks[]` list.
 *   3. Sort matches by RSSI (strongest first).
 *   4. Try each in turn until one connects.
 *
 * The credentials list is generated by `./build.sh` from
 * senselink.local.conf and lives at generated/wifi_creds_generated.h —
 * never committed.
 */
#include "wifi_skel.h"
#include "wifi_creds_generated.h"

#include <stdio.h>
#include <string.h>
#include "pico/cyw43_arch.h"
#include "pico/stdlib.h"

int wifi_skel_last_pm_rc = -999;

/* ── Scan accumulator ────────────────────────────────────────────────────
 * For each known SSID, track the strongest RSSI seen during the scan.
 */
typedef struct {
    bool   seen;
    int16_t rssi;       /* dBm, more-negative = weaker */
    uint8_t auth_mode;  /* CYW43_AUTH_* */
} scan_hit_t;

static scan_hit_t  g_hits[SENSELINK_NETWORK_COUNT];
static volatile bool g_scan_done = false;

static int scan_cb(void *env, const cyw43_ev_scan_result_t *r) {
    (void)env;
    if (!r || r->ssid_len == 0) return 0;
    /* Match against known list */
    for (int i = 0; i < SENSELINK_NETWORK_COUNT; i++) {
        const char *known = senselink_networks[i].ssid;
        size_t kl = strlen(known);
        if (kl != r->ssid_len) continue;
        if (memcmp(known, r->ssid, kl) != 0) continue;
        /* Match: keep the strongest sighting */
        if (!g_hits[i].seen || r->rssi > g_hits[i].rssi) {
            g_hits[i].seen      = true;
            g_hits[i].rssi      = r->rssi;
            g_hits[i].auth_mode = r->auth_mode;
        }
    }
    return 0;
}

static void run_scan(void) {
    memset(g_hits, 0, sizeof(g_hits));
    g_scan_done = false;
    cyw43_wifi_scan_options_t opts = {0};
    if (cyw43_wifi_scan(&cyw43_state, &opts, NULL, scan_cb) != 0) {
        printf("[wifi] scan kickoff failed\n");
        g_scan_done = true;
        return;
    }
    /* Poll the scan until it completes (roughly 5s). */
    absolute_time_t deadline = make_timeout_time_ms(15000);
    while (cyw43_wifi_scan_active(&cyw43_state)
           && !time_reached(deadline)) {
        sleep_ms(100);
    }
    g_scan_done = true;
}

/* Return the index of the strongest seen known network, or -1. */
static int pick_strongest(void) {
    int best = -1;
    int16_t best_rssi = INT16_MIN;
    for (int i = 0; i < SENSELINK_NETWORK_COUNT; i++) {
        if (!g_hits[i].seen) continue;
        if (g_hits[i].rssi > best_rssi) {
            best = i;
            best_rssi = g_hits[i].rssi;
        }
    }
    return best;
}

/* Mark this index as tried (so we don't retry the same one) by clearing it. */
static void mark_tried(int i) {
    g_hits[i].seen = false;
}

bool wifi_skel_init(void) {
    if (cyw43_arch_init()) {
        printf("[wifi] cyw43_arch_init failed\n");
        return false;
    }
    cyw43_arch_enable_sta_mode();

    if (SENSELINK_NETWORK_COUNT == 0) {
        printf("[wifi] no networks configured (generated header is empty?)\n");
        return false;
    }

    printf("[wifi] scanning for %d known network(s)...\n",
           SENSELINK_NETWORK_COUNT);
    run_scan();

    int seen_count = 0;
    for (int i = 0; i < SENSELINK_NETWORK_COUNT; i++) {
        if (g_hits[i].seen) {
            printf("[wifi]   '%s' rssi=%d dBm auth=0x%02x\n",
                   senselink_networks[i].ssid,
                   g_hits[i].rssi,
                   g_hits[i].auth_mode);
            seen_count++;
        }
    }
    if (seen_count == 0) {
        printf("[wifi] none of the configured networks are in range\n");
        return false;
    }
    printf("[wifi] %d known network(s) in range; trying strongest first\n",
           seen_count);

    /* Try in descending signal-strength order until one connects. */
    for (int attempt = 0; attempt < seen_count; attempt++) {
        int idx = pick_strongest();
        if (idx < 0) break;
        const char *ssid = senselink_networks[idx].ssid;
        const char *psk  = senselink_networks[idx].psk;

        printf("[wifi] connecting to '%s'...\n", ssid);
        int rc = cyw43_arch_wifi_connect_timeout_ms(
            ssid, psk, CYW43_AUTH_WPA2_AES_PSK, 30000);
        if (rc == 0) {
            int pm_rc = cyw43_wifi_pm(&cyw43_state, CYW43_NONE_PM);
            wifi_skel_last_pm_rc = pm_rc;
            printf("[wifi] cyw43_wifi_pm(NONE_PM) returned %d\n", pm_rc);

            extern struct netif *netif_default;
            if (netif_default) {
                printf("[wifi] connected to '%s', ip=%s (pm_rc=%d)\n",
                       ssid, ip4addr_ntoa(netif_ip4_addr(netif_default)), pm_rc);
            } else {
                printf("[wifi] connected to '%s' (no netif?, pm_rc=%d)\n", ssid, pm_rc);
            }
            return true;
        }
        printf("[wifi] connect to '%s' failed (rc=%d); trying next\n",
               ssid, rc);
        mark_tried(idx);
    }

    printf("[wifi] exhausted all in-range known networks\n");
    return false;
}
